USE `game`;
DROP procedure IF EXISTS `WEB_SERVICE_MOBILE_SIGNUP_PUT`;

CREATE procedure WEB_SERVICE_MOBILE_SIGNUP_PUT() 
BEGIN 

  DECLARE ITEM_COST VARCHAR(10); SET ITEM_COST = (SELECT '130.20'); END
