DROP procedure IF EXISTS `WEB_SERVICE_MOBILE_SIGNUP_PUT`;

DELIMITER $$
USE `game`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `WEB_SERVICE_MOBILE_SIGNUP_PUT`(
	USER_ID_VALUE 		VARCHAR(20),
    CFA_ID_VALUE		VARCHAR(20),
    TOKEN_TYPE_VALUE	VARCHAR(3)
)
BEGIN
	
    SELECT NOW();
    
END$$

DELIMITER ;

